services:
  backend-staging:
    image: todo-backend:${BUILD_NUMBER:-latest}
    container_name: backend-staging
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=staging
    networks:
      - devcontainer

  frontend-staging:
    image: todo-frontend:${BUILD_NUMBER:-latest}
    container_name: frontend-staging
    ports:
      - "3001:80"
    depends_on:
      - backend-staging
    networks:
      - devcontainer

networks:
  devcontainer:
    name: jenkins-cicd-lab_devcontainer_default
    external: true
