services:
  backend-prod:
    image: backend:${BUILD_NUMBER:-latest}
    container_name: backend-prod
    ports:
      - "4000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - devcontainer

  frontend-prod:
    image: frontend:${BUILD_NUMBER:-latest}
    container_name: frontend-prod
    ports:
      - "4001:80"
    depends_on:
      - backend-prod
    networks:
      - devcontainer

networks:
  devcontainer:
    name: jenkins-cicd-lab_devcontainer_default
    external: true
